# Generated by Django 5.2.5 on 2025-09-08 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('division1', models.IntegerField(default=0)),
                ('division2', models.IntegerField(default=0)),
                ('division3', models.IntegerField(default=0)),
                ('division4', models.IntegerField(default=0)),
                ('division0', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('gpa', models.FloatField(default=0.0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='app.school')),
            ],
            options={
                'ordering': ['gpa', '-total'],
                'unique_together': {('school', 'exam', 'year')},
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_number', models.CharField(max_length=20)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('aggregate_score', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=5)),
                ('subjects', models.TextField()),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_results', to='app.examresult')),
            ],
            options={
                'unique_together': {('exam_result', 'candidate_number')},
            },
        ),
        migrations.CreateModel(
            name='SubjectResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
                ('registered', models.IntegerField(default=0)),
                ('sat', models.IntegerField(default=0)),
                ('no_ca', models.IntegerField(default=0)),
                ('withheld', models.IntegerField(default=0)),
                ('clean', models.IntegerField(default=0)),
                ('passed', models.IntegerField(default=0)),
                ('gpa', models.FloatField(default=0.0)),
                ('competency_level', models.CharField(blank=True, max_length=50)),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_results', to='app.examresult')),
            ],
            options={
                'ordering': ['gpa'],
                'unique_together': {('exam_result', 'subject_code')},
            },
        ),
    ]
