# Generated by Django 5.2.5 on 2025-11-05 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(default='Unknown', max_length=100)),
                ('district', models.CharField(default='Unknown', max_length=100)),
                ('council', models.CharField(default='Unknown', max_length=100)),
                ('school_type', models.CharField(default='Primary', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('division1', models.IntegerField(default=0)),
                ('division2', models.IntegerField(default=0)),
                ('division3', models.IntegerField(default=0)),
                ('division4', models.IntegerField(default=0)),
                ('division0', models.IntegerField(default=0)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('grade_a', models.IntegerField(default=0)),
                ('grade_b', models.IntegerField(default=0)),
                ('grade_c', models.IntegerField(default=0)),
                ('grade_d', models.IntegerField(default=0)),
                ('grade_e', models.IntegerField(default=0)),
                ('grade_f', models.IntegerField(default=0)),
                ('average_score', models.FloatField(blank=True, null=True)),
                ('performance_level', models.CharField(blank=True, max_length=50)),
                ('total', models.IntegerField(default=0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school')),
            ],
            options={
                'unique_together': {('school', 'exam', 'year')},
            },
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_number', models.CharField(max_length=20)),
                ('prem_number', models.CharField(blank=True, max_length=20)),
                ('sex', models.CharField(max_length=1)),
                ('aggregate_score', models.CharField(max_length=10)),
                ('division', models.CharField(max_length=5)),
                ('subjects', models.TextField()),
                ('average_grade', models.CharField(blank=True, max_length=5)),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.examresult')),
            ],
            options={
                'unique_together': {('exam_result', 'candidate_number')},
            },
        ),
        migrations.CreateModel(
            name='SubjectPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
                ('registered', models.IntegerField(default=0)),
                ('sat', models.IntegerField(default=0)),
                ('no_ca', models.IntegerField(default=0)),
                ('withheld', models.IntegerField(default=0)),
                ('clean', models.IntegerField(default=0)),
                ('passed', models.IntegerField(default=0)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('competency_level', models.CharField(blank=True, max_length=50)),
                ('average_score', models.FloatField(blank=True, null=True)),
                ('proficiency_group', models.CharField(blank=True, max_length=50)),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_performances', to='app.examresult')),
            ],
            options={
                'unique_together': {('exam_result', 'subject_code')},
            },
        ),
    ]
