# Generated by Django 5.2.5 on 2025-08-28 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('center_number', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('CSEE', 'Certificate of Secondary Education Examination'), ('ACSEE', 'Advanced Certificate of Secondary Education Examination')], max_length=10)),
                ('year', models.IntegerField()),
                ('avg_score', models.FloatField(help_text='Average division (lower is better)')),
                ('num_students', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='app.school')),
            ],
            options={
                'unique_together': {('school', 'exam_type', 'year')},
            },
        ),
    ]
