# Generated by Django 5.2.5 on 2025-08-28 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='center_number',
            new_name='code',
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam', models.CharField(max_length=10)),
                ('year', models.IntegerField()),
                ('division1', models.IntegerField(default=0)),
                ('division2', models.IntegerField(default=0)),
                ('division3', models.IntegerField(default=0)),
                ('division4', models.IntegerField(default=0)),
                ('division0', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('average_score', models.FloatField(default=0.0)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='app.school')),
            ],
            options={
                'unique_together': {('school', 'exam', 'year')},
            },
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
