# Generated by Django 5.2.5 on 2025-09-05 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SubjectPerformance',
        ),
    ]
