# Generated by Django 5.2.5 on 2025-09-08 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_subjectresult'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examresult',
            options={},
        ),
        migrations.AlterField(
            model_name='examresult',
            name='gpa',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='examresult',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.school'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='exam_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.examresult'),
        ),
        migrations.AlterField(
            model_name='studentresult',
            name='sex',
            field=models.CharField(max_length=1),
        ),
        migrations.CreateModel(
            name='SubjectPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=10)),
                ('subject_name', models.CharField(max_length=100)),
                ('registered', models.IntegerField(default=0)),
                ('sat', models.IntegerField(default=0)),
                ('no_ca', models.IntegerField(default=0)),
                ('withheld', models.IntegerField(default=0)),
                ('clean', models.IntegerField(default=0)),
                ('passed', models.IntegerField(default=0)),
                ('gpa', models.FloatField(blank=True, null=True)),
                ('competency_level', models.CharField(blank=True, max_length=50)),
                ('exam_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_performances', to='app.examresult')),
            ],
            options={
                'unique_together': {('exam_result', 'subject_code')},
            },
        ),
    ]
